### ISSUE TITLE
Lighthouse suggestions

### ISSUE THREAD

**Issue by FDiskas** [Vagr9K/gatsby-material-starter#24]
Make it better - test it with [lighthouse plugin for chrome](https://chrome.google.com/webstore/detail/lighthouse/blipmdconlkpinefehnmjammfjpmpbjk)
![Lighthouse](https://i.imgur.com/muYVn3E.png)

**Comment by FDiskas** [comment]
This is stock

**Comment by Vagr9K** [comment]
This isn't really an issue since Lighthouse criticizes usage of random image generators (external).

As soon as you replace them with your own content, you get ~90% depending on the used images.

![screenshot_20180207_133218](https://user-images.githubusercontent.com/5121786/35908902-67de79da-0c0b-11e8-9e38-eb0064c26d49.png)

See (my personal blog)[https://vagr9k.me] as a sample (it's using this starter).

That being said, I am keeping this open because usage of `gatsby-images` and some automatic optimization system during the build process is being considered.
