### ISSUE TITLE
Add components testing

### ISSUE THREAD

**Issue by Scot3004** [Vagr9K/gatsby-material-starter#36]
On the starter is not given a test framework but could be good if it have a test suite, for quality

**Comment by Vagr9K** [comment]
Unfortunately due to the way gatsby starters work, you can't use them as separate plugins or NPM packages. This means that you'll have to work on the code written in the starter.

I wanted to initially add unit tests back in summer, but then realized that whoever will try to use my starter, will be stuck with my preferred unit testing system, which he might not like, or just not need.

I appreciate you pointing out the flaws of the project, but until gatsby creates a different starter system, "fixing" this flaw will only limit it's usability.
