### ISSUE TITLE
Refactor SEO Component

### ISSUE THREAD

**Issue by Scot3004** [Vagr9K/gatsby-material-starter#54]
When is needed the creation of new pages is almost unpossible to handle the seo props correctly, at this moment this depends only on the 2 given pages, about and index. should be possible to add new elements to SEO

**Comment by Vagr9K** [comment]
I don't want to write duplicated comments in 7 different places, so I'll address:

https://github.com/Vagr9K/gatsby-material-starter/issues/49
https://github.com/Vagr9K/gatsby-material-starter/issues/56
https://github.com/Vagr9K/gatsby-material-starter/pull/55
https://github.com/Vagr9K/gatsby-material-starter/pull/53
https://github.com/Vagr9K/gatsby-advanced-starter/issues/43
https://github.com/Vagr9K/gatsby-advanced-starter/issues/41

...in this comment.

The issues/PRs that you've opened are although valid, but end up pushing the limits of the project scope.

This project's main job is:

- Allow new Gatsby users to use them as a reference to learn relatively advanced Gatsby techniques
- Provide them with a real-world example
- Show what's possible

When it comes to using the code of this project:

- Users with light needs will modify color-schemes/configuration and achieve pretty much everything they'll ever need
- Moderate users will modify styles/components to their liking (like you are doing right now)
- Advanced users will use the project as a reference for possible implementations, while writing the code from scratch to satisfy their standards

Your issues/PRs focus on giving users with moderate needs more customization options, but they come with trade offs:

- If the `SEO` component gets split between files, navigating the code and seeing usage of `react-helmet` will be much harder. The newcomer will have to constantly mash F12 to find other code references. On top of that, even though the component doesn't cover all the possible use cases, it's still sufficient for 90% of users and provides metadata for all main social platforms/search engines.
- If different pages start receiving `config` as a prop, users with light needs will lose the ability to quickly pull their settings from `SiteConfig` and instead will have to track passing props.
- HOC components will add another layer of complexity (especially for [React newcomers](https://stackoverflow.com/questions/52107039/removing-or-hiding-the-gatsby-starter-toolbar/52136255#52136255), even though I don't recommend learning both React and Gatsby at the same time)

The reality with projects like this is that as much as the contributors add new customization options, there will always be someone that will need more.

I like your style of code (even though I disagree with using too many props) and your contributions improve the features of the project, but with all of the above considered and combined with:

> people are migrating their v2-beta starter based sites to v2 this week (which means that they'll have to do additional migrations/bugfixes with this PR merged in)

...which I said in the previous PR, puts me in a situation where your contributions don't align with my vision of the project and my understanding of user needs.

With all of this being said, if you feel like the project's base aligns with your needs, using your contributions in your own project is objectively the best solution in Gatsbyland, and will provide you with the best results.

Unfortunately creating the best user experience isn't the same as checking all the best practices boxes.

I wish I had time to address your issues before you invested time into creating a PR, but the time difference was less than an hour and then I noticed over 8 notifications across 2 repositories.

I'm currently working on a contribution guide to prevent situations like this in the future.

Thank you for your understanding.

**Comment by Scot3004** [comment]
Yes but as you note if the jsonld is generated in a new place it allows you to add custom metadata for new pages, ( which is easy to do).

The components that I choose for receive props are the components which only uses less than 5 configs or uses url config join which is better to place in just a place, for me the best is the page components.

When I said split post page component and it's real view implement is thinking in MVC where gastby is the model, the pages are the controller and components the views.
I never touched siteConfig file because it's a good idea just I want to have more granularity to improve the extension developer experience, my main Target is reduce the duplicate code.

I noted that my previous pull request was too big and the issue more than a task looks like an epic, that's why I splitted down in most specific issues.

Try to compare your 2 starters, find the similarities and you will note that all this will make easier to maintain them because you can just copy and paste your logic and maintain the specific front end part untouched.

Come on, why I should make a new project if yours almost fit my needs, I just proposed ways to make a better project, and of course retribute you for your efforts.

**Comment by Vagr9K** [comment]
> Yes but as you note if the jsonld is generated in a new place it allows you to add custom metadata for new pages, ( which is easy to do).

I've also said: 

> If the SEO component gets split between files, navigating the code and seeing usage of react-helmet will be much harder. The newcomer will have to constantly mash F12 to find other code references. On top of that, even though the component doesn't cover all the possible use cases, it's still sufficient for 90% of users and provides metadata for all main social platforms/search engines.

More customization isn't always the answer.

> The components that I choose for receive props are the components which only uses less than 5 configs or uses url config join which is better to place in just a place, for me the best is the page components.

Which still breaks the code consistency of:

- SiteConfig is a direct import. No config props are passed since they are global.
- pageNodes/other GraphQL nodes get passed as an object, so adding stuff to queries won't require backtracking every single component and adding new props.

> When I said split post page component and it's real view implement is thinking in MVC where gastby is the model, the pages are the controller and components the views.

As I said, it only sounds good on paper. Real implementation only adds unnecessary complexity.

> I never touched siteConfig file because it's a good idea just I want to have more granularity to improve the extension developer experience, my main Target is reduce the duplicate code.

I don't see any duplicated code that was removed in your PR (+78, -67 lines from stats). 
For one you've introduced more code that needs to be maintained.

> I noted that my previous pull request was too big and the issue more than a task looks like an epic, that's why I splitted down in most specific issues.

I appreciate your efforts, but you ignored the part where I said:

> All of this combined with that fact that people are migrating their v2-beta starter based sites to v2 this week (which means that they'll have to do additional migrations/bugfixes with this PR merged in), just doesn't convince me in this PR improving the project quality or the developer experience.
> I really appreciate your contribution, but I feel like it's going to benefit your own website more for your own specific use case, than the material starter as a whole.

This was the main reason for rejection, not the PR size.

> Try to compare your 2 starters, find the similarities and you will note that all this will make easier to maintain them because you can just copy and paste your logic and maintain the specific front end part untouched.

I've already addressed this [here](https://github.com/Vagr9K/gatsby-advanced-starter/issues/44#issuecomment-422949267).

> Come on, why I should make a new project if yours almost fit my needs,

This is not a library that can add new API's for every use case and end up satisfying all users.

This is a code boilerplate, that:

- Allows new Gatsby users to use them as a reference to learn relatively advanced Gatsby techniques
- Provides them with a real-world example
- Shows what's possible
- Gives a base to start with

Imagine if `create-react-app` tried to support every possible use case by its users. It simply wouldn't work, and would end up breaking other, more common workflows.

Your code is great for your own use case. Use it in your own website's code.
Using GM starter's code as a base, modifying it to comply with own needs in their own repo, has been the most reliable method for all Gatsby users across 3 major versions and 2 years.

So far it was working out great for everyone.

**Comment by Vagr9K** [comment]
>> This is not a library that can add new API's for every use case and end up satisfying all users.

> Yes, i know this, just proposed some extensibility changes (rejected)

>> Your code is great for your own use case. Use it in your own website's code.

>Thanks for your ideas, I'll apply them on my website don't dude it.

>Good luck with your project but if my ideas are rejected, I have nothing to do here, cya


I find it interesting that you have deleted your original comment (which was arguably less passive-aggressive):

> Ok, man your vision is just boilerplate, it's ok.
Good luck, it's sad how you just reject any kind of recommendation about QA, but is your project, last comment from my side. I just feel hard to propose improvement task.

I've received this comment via email notifications from GitHub. It was posted on this same thread.

Initially when I posted my criticisms of your PRs, I was hoping for a constructive technical discussion, which unfortunately was absent in the [original issue](https://github.com/Vagr9K/gatsby-material-starter/issues/49), since you ignored my concerns and instantly switched to implementing your proposed changes.

When the [actual PR](https://github.com/Vagr9K/gatsby-material-starter/pull/51) arrived, I just wasn't convinced that it was an improvement, considering the added code complexity. On top of that, your PR description made zero effort to show any practical usages where it made considerable improvements to user experience.

I wrote a [very detailed explanation](https://github.com/Vagr9K/gatsby-material-starter/pull/51#issuecomment-422349493) of why I have to reject your PR.

Later you've split your PR into two (#53, #55), citing the size as a rejection reason (when it wasn't, especially since I've never mentioned PR size in my comments), while not (or barely) addressing my concerns.

Yet again I've written [another even more detailed explanation](https://github.com/Vagr9K/gatsby-material-starter/issues/54#issuecomment-422986708) of my concerns, to which you replied by reciting your ideas while not providing any arguments in their favor, except for very generic "it's easier/it's better".

I've also replied to issues that you have created and [explained](https://github.com/Vagr9K/gatsby-advanced-starter/issues/44#issuecomment-422949267) the reasoning for me to defer their implementation (especially since some of them were proposed and discussed by other users a year ago), while [implementing fixes](https://github.com/Vagr9K/gatsby-advanced-starter/issues/42#issuecomment-423537153) for others.

A [Contributor's Guide](https://github.com/Vagr9K/gatsby-material-starter/issues/57) has also been [suggested](https://github.com/Vagr9K/gatsby-material-starter/issues/54#issuecomment-422986708) and [added](https://github.com/Vagr9K/gatsby-material-starter/pull/59) by me, to minimize the chances of situations like these in the future.

Criticizing code/suggestions to keep the project quality high is my main job as a maintainer. 
Your two previous PRs aligned with the requirements of this project and and I happily merged them while thanking you for your contributions (#45, #48).
The last 3 pull requests by you (#55, #53, #51), weren't as convincing.

Considering your latest:

> Good luck with your project but if my ideas are rejected, I have nothing to do here, cya 

 passive-aggressive comment, I do believe that we won't see any technical discussions here at this point, hence I'm locking this issue since the conversation is no longer constructive.
